/* FACEBOOK */
export const GET_FACEBOOK_MESSAGES_PENDING = 'GET_FACEBOOK_MESSAGES_PENDING';
export const GET_FACEBOOK_MESSAGES_SUCCESS = 'GET_FACEBOOK_MESSAGES_SUCCESS';
export const GET_FACEBOOK_MESSAGES_ERROR = 'GET_FACEBOOK_MESSAGES_ERROR'

export const GET_FACEBOOK_MESSAGE_PENDING ='GET_FACEBOOK_MESSAGE_PENDING';
export const GET_FACEBOOK_MESSAGE_SUCCESS ='GET_FACEBOOK_MESSAGE_SUCCESS';
export const GET_FACEBOOK_MESSAGE_ERROR = 'GET_FACEBOOK_MESSAGE_ERROR';

/* TWITTER */
export const GET_TWITTER_MESSAGES_PENDING = 'GET_TWITTER_MESSAGES_PENDING';
export const GET_TWITTER_MESSAGES_SUCCESS = 'GET_TWITTER_MESSAGES_SUCCESS';
export const GET_TWITTER_MESSAGES_ERROR = 'GET_TWITTER_MESSAGES_ERROR'

/* TO DO TWEET */
export const GET_TWITTER_MESSAGE_PENDING = 'GET_TWITTER_MESSAGE_PENDING';
export const GET_TWITTER_MESSAGE_SUCCESS = 'GET_TWITTER_MESSAGE_SUCCESS';
export const GET_TWITTER_MESSAGE_ERROR = 'GET_TWITTER_MESSAGE_ERROR'

/* AUTHENTICATION */
export const AUTH_PENDING = 'AUTH_PENDING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';


/* USER */
export const GET_USER_INFO_PENDING = 'GET_USER_INFO_PENDING';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';
